test_name: Signup, Login, Create ToDo, Set priority, Delete ToDo, Logout

stages:
  - name: Make sure we have the right Database (Must be test)
    request:
      url: http://localhost:8080/api/v1/db
      method: GET
    response:
      status_code: 200
      body:
        name: test

  - name: Make sure only get method can be used for DB
    request:
      url: http://localhost:8080/api/v1/db
      method: POST
    response:
      status_code: 404
      body:
        error: Wrong Method
