test_name: Signup, Login, Create ToDo, Set priority, Delete ToDo, Logout

stages:
  - name: Make sure we have the right ID
    request:
      url: http://jsonplaceholder.typicode.com/posts/1
      method: GET
    response:
      status_code: 200
      body:
        id: 1
      save:
        body:
          returned_id: id
